/**
 * Generate interop test vectors for the node-side private-space crypto.
 *
 * Replicates EXACTLY what feed-client/src/lib/{x25519,encryption}.ts do, using the
 * same @noble primitives + WebCrypto AES-GCM, with FIXED nonces/ivs so the output is
 * deterministic. Emits a Rust test file (src/crypto/private_space_vectors.rs) that
 * locks the Rust impl to these byte formats.
 *
 * Run from the feed-client dir (so @noble resolves):
 *   node gen-vectors.mjs > ../src/crypto/private_space_vectors.rs
 */
import { x25519, ed25519 } from '@noble/curves/ed25519';
import { sha512 } from '@noble/hashes/sha512';
import { xsalsa20poly1305 } from '@noble/ciphers/salsa.js';

const hex = (u8) => Buffer.from(u8).toString('hex');

// ---- ed25519 seed -> X25519 secret (matches x25519.ts ed25519PrivateToX25519) ----
function seedToX25519Secret(seed) {
  const h = sha512(seed);
  const sk = new Uint8Array(h.slice(0, 32));
  sk[0] &= 248;
  sk[31] = (sk[31] & 127) | 64;
  return sk;
}

// ---- ed25519 pub -> X25519 pub: the client's OWN birational impl (convertEdPublicToX25519) ----
function edPublicToX25519(edPk) {
  const p = BigInt('57896044618658097711785492504343953926634992332820282019728792003956564819949');
  let y = 0n;
  for (let i = 0; i < 32; i++) y |= BigInt(edPk[i]) << BigInt(8 * i);
  y &= (1n << 255n) - 1n;
  const mod = (a, m) => ((a % m) + m) % m;
  const modInverse = (a, m) => {
    let [or, r] = [a, m], [os, s] = [1n, 0n];
    while (r !== 0n) { const q = or / r; [or, r] = [r, or - q * r]; [os, s] = [s, os - q * s]; }
    return mod(os, m);
  };
  const u = mod(mod(1n + y, p) * modInverse(mod(1n - y, p), p), p);
  const out = new Uint8Array(32);
  let t = u;
  for (let i = 0; i < 32; i++) { out[i] = Number(t & 0xffn); t >>= 8n; }
  return out;
}

const enc = new TextEncoder();

// Fixed inputs.
const SEED = Uint8Array.from({ length: 32 }, (_, i) => (i * 7 + 3) & 0xff);
const skX = seedToX25519Secret(SEED);
const pkX = x25519.getPublicKey(skX);
const edPub = ed25519.getPublicKey(SEED);
const x25519FromEdPub = edPublicToX25519(edPub);

// Box (self-wrap a 32-byte space key) with a FIXED nonce.
const SPACE_KEY = Uint8Array.from({ length: 32 }, (_, i) => (255 - i) & 0xff);
const BOX_NONCE = Uint8Array.from({ length: 24 }, (_, i) => (i * 11 + 1) & 0xff);
const shared = x25519.getSharedSecret(skX, pkX);
const boxCt = xsalsa20poly1305(shared, BOX_NONCE).encrypt(SPACE_KEY);
const boxed = new Uint8Array(24 + boxCt.length);
boxed.set(BOX_NONCE, 0);
boxed.set(boxCt, 24);

// AES-256-GCM with fixed key + fixed IV (matches encryption.ts iv||ct format).
const AES_KEY = Uint8Array.from({ length: 32 }, (_, i) => (i * 3 + 5) & 0xff);
const GCM_IV = Uint8Array.from({ length: 12 }, (_, i) => (i * 5 + 2) & 0xff);
const CONTENT = 'hello\n\nworld — private';
const NAME = 'Project Team ✓';

async function aesGcm(keyBytes, iv, plaintext) {
  const key = await crypto.subtle.importKey('raw', keyBytes, { name: 'AES-GCM' }, false, ['encrypt']);
  const ct = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, plaintext));
  const blob = new Uint8Array(iv.length + ct.length);
  blob.set(iv, 0);
  blob.set(ct, iv.length);
  return blob;
}

const contentBlob = await aesGcm(AES_KEY, GCM_IV, enc.encode(CONTENT));
const contentFramed = `[PRIVATE:v1:${Buffer.from(contentBlob).toString('base64')}]`;
const nameBlob = await aesGcm(AES_KEY, GCM_IV, enc.encode(NAME));

const rustEscape = (s) => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

process.stdout.write(`// @generated by feed-client/gen-vectors.mjs — DO NOT EDIT BY HAND.
// Interop vectors captured from the JS clients (@noble + WebCrypto), locking the Rust
// private-space crypto to the exact byte formats the browser clients produce/consume.

#[test]
fn interop_vectors_match_js() {
    let h = |s: &str| hex::decode(s).unwrap();

    let seed: [u8; 32] = h("${hex(SEED)}").try_into().unwrap();

    // ed25519 seed -> X25519 secret / public
    assert_eq!(super::ed25519_seed_to_x25519_secret(&seed).to_vec(), h("${hex(skX)}"), "x25519 secret");
    let sk: [u8; 32] = h("${hex(skX)}").try_into().unwrap();
    assert_eq!(super::x25519_public_from_secret(&sk).to_vec(), h("${hex(pkX)}"), "x25519 public");

    // ed25519 public -> X25519 public
    let ed_pub: [u8; 32] = h("${hex(edPub)}").try_into().unwrap();
    assert_eq!(super::ed25519_public_to_x25519(&ed_pub).unwrap().to_vec(), h("${hex(x25519FromEdPub)}"), "ed->x25519 pub");

    // NaCl box (raw-DH key) with fixed nonce must reproduce the JS ciphertext exactly.
    let pk: [u8; 32] = h("${hex(pkX)}").try_into().unwrap();
    let nonce: [u8; 24] = h("${hex(BOX_NONCE)}").try_into().unwrap();
    let space_key: [u8; 32] = h("${hex(SPACE_KEY)}").try_into().unwrap();
    let boxed = super::x25519_box_with_nonce(&space_key, &pk, &sk, &nonce);
    assert_eq!(boxed, h("${hex(boxed)}"), "x25519 box bytes");
    // ...and the node can unbox a JS-format box back to the space key.
    assert_eq!(super::x25519_unbox(&h("${hex(boxed)}"), &pk, &sk).unwrap(), space_key.to_vec(), "x25519 unbox");

    // AES-256-GCM with fixed IV must reproduce the JS blob exactly.
    let aes_key: [u8; 32] = h("${hex(AES_KEY)}").try_into().unwrap();
    let iv: [u8; 12] = h("${hex(GCM_IV)}").try_into().unwrap();
    assert_eq!(super::aes_gcm_encrypt_with_iv("${rustEscape(CONTENT)}".as_bytes(), &aes_key, &iv), h("${hex(contentBlob)}"), "aes-gcm blob");

    // The node decrypts JS-produced framed content and raw name blobs.
    assert_eq!(super::decrypt_content_with_space_key("${rustEscape(contentFramed)}", &aes_key).unwrap(), "${rustEscape(CONTENT)}", "decrypt JS content");
    assert_eq!(super::decrypt_space_name(&h("${hex(nameBlob)}"), &aes_key).unwrap(), "${rustEscape(NAME)}", "decrypt JS name");
}
`);
