# ChainSocial Mobile - iOS Podfile
# Minimum iOS 15.0 for modern features

platform :ios, '15.0'

# Prepare React Native
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'ChainSocialMobile' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    # Flipper configuration
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Argon2 library for PoW
  pod 'Argon2Swift', '~> 1.0'

  # Gesture handler
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  # Reanimated
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  # Haptic feedback
  pod 'react-native-haptic-feedback', :path => '../node_modules/react-native-haptic-feedback'

  # Async storage
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  # Network info
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  # Safe area
  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  # Screens
  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  # SVG
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # Fix deployment target warning
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end
