// @generated by feed-client/gen-vectors.mjs — DO NOT EDIT BY HAND.
// Interop vectors captured from the JS clients (@noble + WebCrypto), locking the Rust
// private-space crypto to the exact byte formats the browser clients produce/consume.

#[test]
fn interop_vectors_match_js() {
    let h = |s: &str| hex::decode(s).unwrap();

    let seed: [u8; 32] = h("030a11181f262d343b424950575e656c737a81888f969da4abb2b9c0c7ced5dc").try_into().unwrap();

    // ed25519 seed -> X25519 secret / public
    assert_eq!(super::ed25519_seed_to_x25519_secret(&seed).to_vec(), h("c0902ef600c188f0a9b0d32d5e78edf886d61887e698a81aab084c8f86dbfe6f"), "x25519 secret");
    let sk: [u8; 32] = h("c0902ef600c188f0a9b0d32d5e78edf886d61887e698a81aab084c8f86dbfe6f").try_into().unwrap();
    assert_eq!(super::x25519_public_from_secret(&sk).to_vec(), h("be2b8b75b369b8f459b8b153799bc5ab07a2f8feba04c11cc843d19fe55ae25c"), "x25519 public");

    // ed25519 public -> X25519 public
    let ed_pub: [u8; 32] = h("755c4cb9256ca7cdc4acfdc6cfeeda849017e5b9f9514e99191bd67e0b0d4276").try_into().unwrap();
    assert_eq!(super::ed25519_public_to_x25519(&ed_pub).unwrap().to_vec(), h("be2b8b75b369b8f459b8b153799bc5ab07a2f8feba04c11cc843d19fe55ae25c"), "ed->x25519 pub");

    // NaCl box (raw-DH key) with fixed nonce must reproduce the JS ciphertext exactly.
    let pk: [u8; 32] = h("be2b8b75b369b8f459b8b153799bc5ab07a2f8feba04c11cc843d19fe55ae25c").try_into().unwrap();
    let nonce: [u8; 24] = h("010c17222d38434e59646f7a85909ba6b1bcc7d2dde8f3fe").try_into().unwrap();
    let space_key: [u8; 32] = h("fffefdfcfbfaf9f8f7f6f5f4f3f2f1f0efeeedecebeae9e8e7e6e5e4e3e2e1e0").try_into().unwrap();
    let boxed = super::x25519_box_with_nonce(&space_key, &pk, &sk, &nonce);
    assert_eq!(boxed, h("010c17222d38434e59646f7a85909ba6b1bcc7d2dde8f3fe40b13d51c0c059b110e1e7579effd26ae1b795cc315836c3c9ed1d61b14179f80f240512b41202176376866ba382452d"), "x25519 box bytes");
    // ...and the node can unbox a JS-format box back to the space key.
    assert_eq!(super::x25519_unbox(&h("010c17222d38434e59646f7a85909ba6b1bcc7d2dde8f3fe40b13d51c0c059b110e1e7579effd26ae1b795cc315836c3c9ed1d61b14179f80f240512b41202176376866ba382452d"), &pk, &sk).unwrap(), space_key.to_vec(), "x25519 unbox");

    // AES-256-GCM with fixed IV must reproduce the JS blob exactly.
    let aes_key: [u8; 32] = h("05080b0e1114171a1d202326292c2f3235383b3e4144474a4d505356595c5f62").try_into().unwrap();
    let iv: [u8; 12] = h("02070c11161b20252a2f3439").try_into().unwrap();
    assert_eq!(super::aes_gcm_encrypt_with_iv("hello

world — private".as_bytes(), &aes_key, &iv), h("02070c11161b20252a2f3439fabb64e8882f980a52232235cbb4391c2f76e6e519113bbdb5a8012618fe1dab30d7099766440edb"), "aes-gcm blob");

    // The node decrypts JS-produced framed content and raw name blobs.
    assert_eq!(super::decrypt_content_with_space_key("[PRIVATE:v1:AgcMERYbICUqLzQ5+rtk6IgvmApSIyI1y7Q5HC925uUZETu9tagBJhj+Hasw1wmXZkQO2w==]", &aes_key).unwrap(), "hello

world — private", "decrypt JS content");
    assert_eq!(super::decrypt_space_name(&h("02070c11161b20252a2f3439c2ac67ee8246e65d69342f3ccbb4251bc7870ff9412a72c3398be475b59efcd6"), &aes_key).unwrap(), "Project Team ✓", "decrypt JS name");
}
