/**
 * WASM module loader for Swimchain
 *
 * Handles lazy loading and initialization of the WASM module.
 * The module is loaded once and cached for subsequent calls.
 */

// Type definition for the WASM module
// These types will be generated by wasm-bindgen, but we define the interface here
export interface WasmModule {
  // Initialization
  init(): void;
  version(): string;

  // Crypto
  sha256(data: Uint8Array): Uint8Array;
  leading_zeros(hash: Uint8Array): number;
  verify_pow_difficulty(hash: Uint8Array, difficulty: number): boolean;
  content_id(data: Uint8Array): string;
  double_sha256(data: Uint8Array): Uint8Array;

  // Identity
  WasmKeypair: {
    new (): WasmKeypair;
    fromSeed(seed: Uint8Array): WasmKeypair;
  };
  encode_address(publicKey: Uint8Array): string;
  decode_address(address: string): Uint8Array;
  verify_signature(
    pubkey: Uint8Array,
    message: Uint8Array,
    signature: Uint8Array
  ): boolean;
  is_valid_address(address: string): boolean;

  // Decay
  calculate_decay(
    createdAtSecs: bigint,
    lastEngagementSecs: bigint,
    nowSecs: bigint
  ): WasmDecayState;
  calculateDecayWithHalfLife(
    createdAtSecs: bigint,
    lastEngagementSecs: bigint,
    nowSecs: bigint,
    halfLifeSecs: bigint | undefined
  ): WasmDecayState;
  getDecayFloorSecs(): bigint;
  getHalfLifeSecs(): bigint;
  getDecayThreshold(): number;

  // PoW
  mine_identity_pow(publicKey: Uint8Array, difficulty: number): WasmPowSolution;
  mineIdentityPowWithLimit(
    publicKey: Uint8Array,
    difficulty: number,
    maxAttempts: bigint
  ): WasmPowSolution;
  verify_identity_pow(
    pubkey: Uint8Array,
    timestamp: bigint,
    nonce: bigint,
    difficulty: number
  ): boolean;
  verifyIdentityPowWithHash(
    pubkey: Uint8Array,
    timestamp: bigint,
    nonce: bigint,
    difficulty: number
  ): Uint8Array | null;
  getDefaultIdentityPowDifficulty(): number;
  estimateMiningTime(difficulty: number, hashRate?: number): number;
}

export interface WasmKeypair {
  publicKey(): Uint8Array;
  seed(): Uint8Array;
  sign(message: Uint8Array): Uint8Array;
  address(): string;
  free(): void;
}

export interface WasmDecayState {
  readonly currentHeat: number;
  readonly isDecayed: boolean;
  readonly isProtected: boolean;
  readonly halfLivesElapsed: number;
  readonly ageSeconds: bigint;
  readonly timeSinceEngagement: bigint;
  decayPercent(): number;
  description(): string;
  timeUntilDecay(): bigint;
  free(): void;
}

export interface WasmPowSolution {
  readonly nonce: bigint;
  readonly attempts: bigint;
  readonly elapsedMs: number;
  readonly timestamp: bigint;
  hash(): Uint8Array;
  leadingZeros(): number;
  hashRate(): number;
  free(): void;
}

// Module state
let wasmModule: WasmModule | null = null;
let initPromise: Promise<WasmModule> | null = null;

/**
 * Initialize the WASM module
 *
 * This must be called before using any WASM functions.
 * Multiple calls are safe - the module is only loaded once.
 *
 * @returns Promise resolving to the initialized WASM module
 *
 * @example
 * ```ts
 * import { initWasm } from '@swimchain/core';
 *
 * await initWasm();
 * // Now WASM functions are available
 * ```
 */
export async function initWasm(): Promise<WasmModule> {
  if (wasmModule) {
    return wasmModule;
  }

  if (initPromise) {
    return initPromise;
  }

  initPromise = (async () => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let wasm: any;

    // Always use the bundled path - Vite will handle the WASM file
    wasm = await import("../pkg/swimchain_wasm.js");
    await wasm.default();

    wasmModule = wasm as WasmModule;
    return wasmModule;
  })();

  return initPromise;
}

/**
 * Get the initialized WASM module
 *
 * @throws Error if WASM is not initialized
 * @returns The WASM module
 *
 * @example
 * ```ts
 * import { getWasm } from '@swimchain/core';
 *
 * const wasm = getWasm();
 * const hash = wasm.sha256(data);
 * ```
 */
export function getWasm(): WasmModule {
  if (!wasmModule) {
    throw new Error(
      "WASM not initialized. Call initWasm() first and await its completion."
    );
  }
  return wasmModule;
}

/**
 * Check if the WASM module is loaded
 *
 * @returns true if WASM is ready to use
 */
export function isWasmLoaded(): boolean {
  return wasmModule !== null;
}

/**
 * Get the WASM library version
 *
 * @throws Error if WASM is not initialized
 * @returns Version string
 */
export function getVersion(): string {
  return getWasm().version();
}
