import{useState,useEffect,useCallback,type FC}from'react';
import{useRpc}from'../hooks/useRpc';
import{useIdentityContext}from'@swimchain/frontend';
interface P{contentId:string;authorId:string;}
export const SponsorshipPanel:FC<P>=({contentId,authorId})=>{const{rpc,connected}=useRpc();const{identity}=useIdentityContext();const[info,setInfo]=useState<{sponsor_id:string|null;status:string;total_stake:number}|null>(null);const[offers,setOffers]=useState<Array<{offer_id:string;title:string;description:string;remaining_stake:number;total_stake:number}>>([]);const[loading,setLoading]=useState(true);const[claiming,setClaiming]=useState(false);const[show,setShow]=useState(false);const isOwn=identity?.publicKey?.toLowerCase()===authorId?.toLowerCase();
useEffect(()=>{if(!rpc||!connected||!contentId){setLoading(false);return}(async()=>{try{const[i,o]=await Promise.all([rpc.getSponsorshipInfo(contentId).catch(()=>null),rpc.listSponsorshipOffers({status:'active',limit:5}).catch(()=>null)]);if(i)setInfo({sponsor_id:i.sponsor_id,status:i.status,total_stake:i.total_stake});if(o)setOffers(o.offers)}catch{}finally{setLoading(false)}})()},[rpc,connected,contentId]);
const claim=useCallback(async(oid:string)=>{if(!rpc||!connected||!identity?.seed||!identity?.publicKey)return;setClaiming(true);try{const{hexToBytes,bytesToHex,wasm}=await import('@swimchain/frontend');const ts=Math.floor(Date.now()/1e3);const sig=wasm.WasmKeypair.fromSeed(hexToBytes(identity.seed)).sign(new TextEncoder().encode('claim:'+oid+':'+contentId+':'+ts));const r=await rpc.claimSponsorshipOffer({offerId:oid,claimantPk:identity.publicKey,contentId,signature:bytesToHex(sig),powNonce:0,powDifficulty:1,powNonceSpace:'',powHash:'',timestamp:ts});if(r.status==='claimed'||r.status==='pending'){setInfo(p=>p?{...p,status:'sponsored'}:{sponsor_id:identity.publicKey,status:'sponsored',total_stake:0});setShow(false)}}catch{}finally{setClaiming(false)}},[rpc,connected,identity,contentId]);
if(loading)return<></>;if(info?.status==='sponsored'||info?.status==='active')return<span style={{fontSize:'.65rem',background:'#fff3cd',color:'#856404',padding:'.15rem .4rem',borderRadius:'4px'}}>? Sponsored</span>;if(!isOwn)return<></>;
return<span style={{position:'relative',display:'inline-flex',alignItems:'center'}}>
<button onClick={()=>setShow(!show)} style={{fontSize:'.65rem',padding:'.15rem .4rem',border:'1px solid #5865f2',borderRadius:'4px',background:'transparent',color:'#5865f2',cursor:'pointer'}}>{show?'Hide':'Get sponsored'}</button>
{show&&<div style={{position:'absolute',top:'100%',left:0,zIndex:10,background:'#fff',border:'1px solid #ddd',borderRadius:'4px',padding:'.5rem',minWidth:'200px',boxShadow:'0 4px 12px rgba(0,0,0,.1)'}}>
{offers.length===0&&<span style={{fontSize:'.7rem',color:'#999'}}>No offers</span>}
{offers.map(o=><div key={o.offer_id} style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:'.5rem',fontSize:'.7rem',padding:'.25rem 0'}}><span>{o.title} ({o.remaining_stake}/{o.total_stake})</span><button onClick={()=>claim(o.offer_id)} disabled={claiming} style={{fontSize:'.65rem',padding:'.15rem .4rem',border:'none',borderRadius:'4px',background:'#3ba55c',color:'#fff',cursor:'pointer'}}>Claim</button></div>)}
</div>}</span>;};
