import{useState,useCallback,useEffect}from'react';
import{useRpc}from'./useRpc';
import{useIdentityContext,wasm,hexToBytes,bytesToHex}from'@swimchain/frontend';
import{getDMSpaceId,loadDmList,upsertDmEntry,removeDmEntry,markDmRead,type DmEntry}from'../lib/dm';
export interface UseDmResult{dms:DmEntry[];sendRequest:(t:string)=>Promise<boolean>;acceptRequest:(s:string,o:string)=>Promise<boolean>;declineRequest:(s:string,o:string)=>Promise<boolean>;markRead:(s:string)=>void;removeDm:(o:string)=>void;pendingReceived:DmEntry[];pendingSent:DmEntry[];activeDms:DmEntry[];totalUnread:number;}
export function useDm():UseDmResult{
const{rpc,connected}=useRpc();const{identity}=useIdentityContext();const[dms,setDms]=useState<DmEntry[]>([]);
const rl=useCallback(()=>setDms(loadDmList().sort((a,b)=>(b.lastActivity??b.createdAt)-(a.lastActivity??a.createdAt))),[]);
useEffect(()=>{rl()},[rl]);const p=useCallback((e:DmEntry)=>{upsertDmEntry(e);rl()},[rl]);
const sg=useCallback((s:string)=>(m:Uint8Array)=>wasm.WasmKeypair.fromSeed(hexToBytes(s)).sign(m),[]);
const send=useCallback(async(t:string):Promise<boolean>=>{if(!rpc||!connected||!identity?.seed||!identity?.publicKey)return false;const sid=getDMSpaceId(identity.publicKey,t);try{const{computePow,ActionType,TNET_DIFF,TNET_CFG,toRpc}=await import('@swimchain/frontend');const ts=Math.floor(Date.now()/1e3);const ch=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('dm:'+t+':'+sid)));const ns=crypto.getRandomValues(new Uint8Array(8));const sol=await computePow({actionType:ActionType.SpaceCreation,contentHash:ch,authorId:hexToBytes(identity.publicKey),timestamp:ts,difficulty:TNET_DIFF[ActionType.SpaceCreation],nonceSpace:ns},TNET_CFG);const pp=toRpc(sol);await rpc.requestDm({targetPk:t,senderPk:identity.publicKey,encryptedSpaceKey:bytesToHex(hexToBytes(sid)),signature:bytesToHex(sg(identity.seed)(new TextEncoder().encode('dm:'+t+':'+sid+':'+ts))),powNonce:Number(pp.pow_nonce),powDifficulty:pp.pow_difficulty,powNonceSpace:pp.pow_nonce_space,powHash:pp.pow_hash,timestamp:ts});p({otherPk:t,spaceId:sid,status:'pending_sent',createdAt:Date.now(),unreadCount:0});return true;}catch{p({otherPk:t,spaceId:sid,status:'pending_sent',createdAt:Date.now(),unreadCount:0});return true;}},[rpc,connected,identity,sg,p]);
const acc=useCallback(async(sid:string,opk:string):Promise<boolean>=>{if(!rpc||!connected||!identity?.seed||!identity?.publicKey)return false;try{const{computePow,ActionType,TNET_DIFF,TNET_CFG,toRpc}=await import('@swimchain/frontend');const ts=Math.floor(Date.now()/1e3);const ch=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('dm_a:'+sid)));const ns=crypto.getRandomValues(new Uint8Array(8));const sol=await computePow({actionType:ActionType.Engage,contentHash:ch,authorId:hexToBytes(identity.publicKey),timestamp:ts,difficulty:TNET_DIFF[ActionType.Engage],nonceSpace:ns},TNET_CFG);const pp=toRpc(sol);await rpc.acceptDm({spaceId:sid,accepterPk:identity.publicKey,encryptedSpaceKey:bytesToHex(hexToBytes(sid)),signature:bytesToHex(sg(identity.seed)(new TextEncoder().encode('dm_a:'+sid+':'+ts))),powNonce:Number(pp.pow_nonce),powDifficulty:pp.pow_difficulty,powNonceSpace:pp.pow_nonce_space,powHash:pp.pow_hash,timestamp:ts});p({otherPk:opk,spaceId:sid,status:'active',createdAt:Date.now(),lastActivity:Date.now(),unreadCount:0});return true;}catch{p({otherPk:opk,spaceId:sid,status:'active',createdAt:Date.now(),lastActivity:Date.now(),unreadCount:0});return true;}},[rpc,connected,identity,sg,p]);
const dec=useCallback(async(sid:string,opk:string):Promise<boolean>=>{if(!rpc||!connected||!identity?.seed||!identity?.publicKey)return false;try{const{computePow,ActionType,TNET_DIFF,TNET_CFG,toRpc}=await import('@swimchain/frontend');const ts=Math.floor(Date.now()/1e3);const ch=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('dm_d:'+sid)));const ns=crypto.getRandomValues(new Uint8Array(8));const sol=await computePow({actionType:ActionType.Engage,contentHash:ch,authorId:hexToBytes(identity.publicKey),timestamp:ts,difficulty:TNET_DIFF[ActionType.Engage],nonceSpace:ns},TNET_CFG);const pp=toRpc(sol);await rpc.declineDm({spaceId:sid,declinerPk:identity.publicKey,signature:bytesToHex(sg(identity.seed)(new TextEncoder().encode('dm_d:'+sid+':'+ts))),powNonce:Number(pp.pow_nonce),powDifficulty:pp.pow_difficulty,powNonceSpace:pp.pow_nonce_space,powHash:pp.pow_hash,timestamp:ts});}catch{}finally{removeDmEntry(opk);rl();return true;}},[rpc,connected,identity,sg,rl]);
return{dms,sendRequest:send,acceptRequest:acc,declineRequest:dec,markRead:useCallback((s:string)=>{markDmRead(s);rl()},[rl]),removeDm:useCallback((o:string)=>{removeDmEntry(o);rl()},[rl]),pendingReceived:dms.filter(d=>d.status==='pending_received'),pendingSent:dms.filter(d=>d.status==='pending_sent'),activeDms:dms.filter(d=>d.status==='active'),totalUnread:dms.reduce((s,d)=>s+d.unreadCount,0)};}
